//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sandbox_BasedEntities : DbContext
    {
        public Sandbox_BasedEntities()
            : base("name=Sandbox_BasedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MemberHierarchyViewC> MemberHierarchyViewCs { get; set; }
        public virtual DbSet<tbl_2Fa> tbl_2Fa { get; set; }
        public virtual DbSet<tbl_AppToken> tbl_AppToken { get; set; }
        public virtual DbSet<tbl_ChecksumBalance> tbl_ChecksumBalance { get; set; }
        public virtual DbSet<tbl_Config_Sms> tbl_Config_Sms { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Current_Login> tbl_Current_Login { get; set; }
        public virtual DbSet<tbl_EmailVerification> tbl_EmailVerification { get; set; }
        public virtual DbSet<tbl_log_action> tbl_log_action { get; set; }
        public virtual DbSet<tbl_log_ChangePassword> tbl_log_ChangePassword { get; set; }
        public virtual DbSet<tbl_log_error> tbl_log_error { get; set; }
        public virtual DbSet<tbl_log_login> tbl_log_login { get; set; }
        public virtual DbSet<tbl_log_SecurityAttemp> tbl_log_SecurityAttemp { get; set; }
        public virtual DbSet<tbl_log_securityPassAttemp> tbl_log_securityPassAttemp { get; set; }
        public virtual DbSet<tbl_log_SendMail> tbl_log_SendMail { get; set; }
        public virtual DbSet<tbl_log_sql> tbl_log_sql { get; set; }
        public virtual DbSet<tbl_log_TacAttemp> tbl_log_TacAttemp { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<tbl_loginAttempt> tbl_loginAttempt { get; set; }
        public virtual DbSet<tbl_Master_BankList> tbl_Master_BankList { get; set; }
        public virtual DbSet<tbl_MemberControl> tbl_MemberControl { get; set; }
        public virtual DbSet<tbl_MemberInfo_Avatar> tbl_MemberInfo_Avatar { get; set; }
        public virtual DbSet<tbl_MemberInfo_Bank> tbl_MemberInfo_Bank { get; set; }
        public virtual DbSet<tbl_MemberUnit> tbl_MemberUnit { get; set; }
        public virtual DbSet<tbl_Merchant_Sms> tbl_Merchant_Sms { get; set; }
        public virtual DbSet<tbl_Parameter> tbl_Parameter { get; set; }
        public virtual DbSet<tbl_ResetPassword> tbl_ResetPassword { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Sms_History> tbl_Sms_History { get; set; }
        public virtual DbSet<tbl_TAC> tbl_TAC { get; set; }
        public virtual DbSet<tbl_WalletCash> tbl_WalletCash { get; set; }
        public virtual DbSet<tbl_EmailQueue> tbl_EmailQueue { get; set; }
        public virtual DbSet<tbl_RememberMeToken> tbl_RememberMeToken { get; set; }
        public virtual DbSet<tbl_ApiRequestLog> tbl_ApiRequestLog { get; set; }
        public virtual DbSet<tbl_Config_General> tbl_Config_General { get; set; }
        public virtual DbSet<tbl_MemberBalance> tbl_MemberBalance { get; set; }
        public virtual DbSet<tbl_Merchant> tbl_Merchant { get; set; }
        public virtual DbSet<tbl_RunningNumber> tbl_RunningNumber { get; set; }
        public virtual DbSet<tbl_Relationship> tbl_Relationship { get; set; }
        public virtual DbSet<tbl_Type_Of_Property> tbl_Type_Of_Property { get; set; }
        public virtual DbSet<tbl_Type_Of_Land> tbl_Type_Of_Land { get; set; }
        public virtual DbSet<tbl_Bank_Account_Type> tbl_Bank_Account_Type { get; set; }
        public virtual DbSet<tbl_Type_Of_Title> tbl_Type_Of_Title { get; set; }
        public virtual DbSet<tbl_UnitTrust_Account_Type> tbl_UnitTrust_Account_Type { get; set; }
        public virtual DbSet<tbl_Funeral_Method> tbl_Funeral_Method { get; set; }
        public virtual DbSet<tbl_Type_Of_Identity> tbl_Type_Of_Identity { get; set; }
        public virtual DbSet<tbl_Type_Of_Executor> tbl_Type_Of_Executor { get; set; }
        public virtual DbSet<tbl_Type_Of_Asset_Allocation> tbl_Type_Of_Asset_Allocation { get; set; }
        public virtual DbSet<tbl_Religion> tbl_Religion { get; set; }
        public virtual DbSet<tbl_Type_Of_Payment_To_Trustee> tbl_Type_Of_Payment_To_Trustee { get; set; }
        public virtual DbSet<tbl_AgentRank> tbl_AgentRank { get; set; }
        public virtual DbSet<tbl_FileUploadAudit> tbl_FileUploadAudit { get; set; }
        public virtual DbSet<tbl_Resource> tbl_Resource { get; set; }
        public virtual DbSet<tbl_ResourceCategory> tbl_ResourceCategory { get; set; }
        public virtual DbSet<tbl_ResourceRole> tbl_ResourceRole { get; set; }
        public virtual DbSet<tbl_MemberUnit_Trust> tbl_MemberUnit_Trust { get; set; }
        public virtual DbSet<tbl_MemberUnit_Will> tbl_MemberUnit_Will { get; set; }
        public virtual DbSet<tbl_Reference> tbl_Reference { get; set; }
        public virtual DbSet<tbl_log_FileUpload> tbl_log_FileUpload { get; set; }
        public virtual DbSet<tbl_MemberInfo_KYC> tbl_MemberInfo_KYC { get; set; }
        public virtual DbSet<tbl_RegistrationSession> tbl_RegistrationSession { get; set; }
        public virtual DbSet<tbl_TrustCategories> tbl_TrustCategories { get; set; }
        public virtual DbSet<tbl_TrustPlan> tbl_TrustPlan { get; set; }
        public virtual DbSet<tbl_TrustPlanBenefit> tbl_TrustPlanBenefit { get; set; }
        public virtual DbSet<tbl_TrustPlanBonusConfig> tbl_TrustPlanBonusConfig { get; set; }
        public virtual DbSet<tbl_TrustPlanCommissionConfig> tbl_TrustPlanCommissionConfig { get; set; }
        public virtual DbSet<tbl_TrustPlanCommissionOneOffTier> tbl_TrustPlanCommissionOneOffTier { get; set; }
        public virtual DbSet<tbl_TrustPlanCommissionRule> tbl_TrustPlanCommissionRule { get; set; }
        public virtual DbSet<tbl_TrustPlanDividendConfig> tbl_TrustPlanDividendConfig { get; set; }
        public virtual DbSet<tbl_TrustPlanDividendInvestmentPeriodTier> tbl_TrustPlanDividendInvestmentPeriodTier { get; set; }
        public virtual DbSet<tbl_TrustPlanDividendInvestmentPeriodTierRate> tbl_TrustPlanDividendInvestmentPeriodTierRate { get; set; }
        public virtual DbSet<tbl_TrustPlanDividendPayout> tbl_TrustPlanDividendPayout { get; set; }
        public virtual DbSet<tbl_TrustPlanExecutionRank> tbl_TrustPlanExecutionRank { get; set; }
        public virtual DbSet<tbl_TrustPlanFee> tbl_TrustPlanFee { get; set; }
        public virtual DbSet<tbl_TrustPlanPaymentConfig> tbl_TrustPlanPaymentConfig { get; set; }
        public virtual DbSet<tbl_TrustPlanWithdrawalConfig> tbl_TrustPlanWithdrawalConfig { get; set; }
        public virtual DbSet<tbl_MemberInfo> tbl_MemberInfo { get; set; }
        public virtual DbSet<tbl_TrustApplication> tbl_TrustApplication { get; set; }
        public virtual DbSet<tbl_TrustApplication_PersonalDetail> tbl_TrustApplication_PersonalDetail { get; set; }
        public virtual DbSet<tbl_TrustApplication_SourceOfFund> tbl_TrustApplication_SourceOfFund { get; set; }
        public virtual DbSet<tbl_TrustApplication_TrustAsset> tbl_TrustApplication_TrustAsset { get; set; }
        public virtual DbSet<tbl_TrustApplication_BeneficiaryAllocation> tbl_TrustApplication_BeneficiaryAllocation { get; set; }
        public virtual DbSet<tbl_TrustApplication_BeneficiaryAllocationDetail> tbl_TrustApplication_BeneficiaryAllocationDetail { get; set; }
        public virtual DbSet<tbl_TrustApplication_TrustDeedExecution> tbl_TrustApplication_TrustDeedExecution { get; set; }
        public virtual DbSet<tbl_TrustApplication_CoBroker> tbl_TrustApplication_CoBroker { get; set; }
        public virtual DbSet<tbl_TrustApplication_SupportingDocument> tbl_TrustApplication_SupportingDocument { get; set; }
        public virtual DbSet<tbl_TrustApplication_Caretaker> tbl_TrustApplication_Caretaker { get; set; }
        public virtual DbSet<tbl_TrustApplication_MinorDistribution> tbl_TrustApplication_MinorDistribution { get; set; }
        public virtual DbSet<tbl_TrustApplication_Beneficiary> tbl_TrustApplication_Beneficiary { get; set; }
        public virtual DbSet<tbl_OpenAiModelPricing> tbl_OpenAiModelPricing { get; set; }
        public virtual DbSet<tbl_OpenAiRequestLog> tbl_OpenAiRequestLog { get; set; }
        public virtual DbSet<tbl_TrustApplication_Payment> tbl_TrustApplication_Payment { get; set; }
        public virtual DbSet<tbl_TrustApplication_PaymentDocument> tbl_TrustApplication_PaymentDocument { get; set; }
        public virtual DbSet<tbl_TrustApplication_StatusHistory> tbl_TrustApplication_StatusHistory { get; set; }
        public virtual DbSet<tbl_TrustApplication_GeneratedDocument> tbl_TrustApplication_GeneratedDocument { get; set; }
        public virtual DbSet<tbl_TrustDocument> tbl_TrustDocument { get; set; }
        public virtual DbSet<tbl_TrustDocumentAllocationMapping> tbl_TrustDocumentAllocationMapping { get; set; }
        public virtual DbSet<tbl_TrustDocumentRole> tbl_TrustDocumentRole { get; set; }
        public virtual DbSet<tbl_TrustDocumentTemplate> tbl_TrustDocumentTemplate { get; set; }
        public virtual DbSet<tbl_TrustApplication_PlanSnapshot> tbl_TrustApplication_PlanSnapshot { get; set; }
        public virtual DbSet<tbl_TrustApplication_DividendSchedule> tbl_TrustApplication_DividendSchedule { get; set; }
        public virtual DbSet<tbl_TrustApplication_History> tbl_TrustApplication_History { get; set; }
    }
}
