//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberHierarchyViewC
    {
        public long RowID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<int> ParentLevel { get; set; }
    }
}
