//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustPlanCommissionOneOffTier
    {
        public long RowID { get; set; }
        public long TrustPlanID { get; set; }
        public string RankCode { get; set; }
        public string CommissionType { get; set; }
        public decimal CommissionRate { get; set; }
        public int Sequence { get; set; }
    }
}
