//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Merchant
    {
        public long RowID { get; set; }
        public string MerchantID { get; set; }
        public string MerchantName { get; set; }
        public string MerchantCode { get; set; }
        public string PrimaryLang { get; set; }
        public string Country_Domain { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string ThemeID { get; set; }
        public string DisplayID { get; set; }
        public string WhatsappHpno { get; set; }
        public string MerchantType { get; set; }
        public int SecondPassword { get; set; }
        public int GoogleTwoFactor { get; set; }
        public int EmailOTP { get; set; }
        public int PhoneOTP { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
        public long AgentID { get; set; }
        public string AntiPhishingCode { get; set; }
        public string Prefix { get; set; }
        public string Mail_Lang { get; set; }
        public string Sms_Lang { get; set; }
    }
}
