//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MemberInfo_Avatar
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public string Avatar { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
        public string FielUrl { get; set; }
    }
}
