//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_TrustAsset
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public decimal TrustAssetAmount { get; set; }
        public string SettlorBankName { get; set; }
        public string SettlorOtherBankName { get; set; }
        public string SettlorBankAccountHolder { get; set; }
        public string SettlorBankAccountNumber { get; set; }
        public string SettlorSwiftCode { get; set; }
        public string SettlorBankAddress { get; set; }
        public string GuaranteedReturnOption { get; set; }
        public string PaymentSource { get; set; }
        public string JointAccountHolderName { get; set; }
        public string ThirdPartyName { get; set; }
        public string ThirdPartyIdentityNo { get; set; }
        public string ThirdPartyRelationship { get; set; }
        public string ThirdPartyOtherRelationship { get; set; }
        public string ThirdPartyBankName { get; set; }
        public string ThirdPartyOtherBankName { get; set; }
        public string ThirdPartyBankAccountHolder { get; set; }
        public string ThirdPartyBankAccountNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
    }
}
