//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailVerification
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public string Email { get; set; }
        public System.DateTime Expired { get; set; }
        public string UniqueID { get; set; }
        public string Signature { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string IP { get; set; }
        public int Status { get; set; }
    }
}
