//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reference
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public string ReferralCode { get; set; }
        public string Type { get; set; }
        public int Ranking { get; set; }
        public int AdvanceRanking { get; set; }
        public int Status { get; set; }
        public string MerchantID { get; set; }
    }
}
