//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OpenAiRequestLog
    {
        public long RowID { get; set; }
        public string RequestType { get; set; }
        public string Source { get; set; }
        public Nullable<long> UserID { get; set; }
        public string MerchantID { get; set; }
        public string OpenAiResponseID { get; set; }
        public string Model { get; set; }
        public Nullable<int> InputTokens { get; set; }
        public Nullable<int> CachedInputTokens { get; set; }
        public Nullable<int> OutputTokens { get; set; }
        public Nullable<int> ReasoningTokens { get; set; }
        public Nullable<int> TotalTokens { get; set; }
        public Nullable<decimal> InputPricePerMillion { get; set; }
        public Nullable<decimal> CachedInputPricePerMillion { get; set; }
        public Nullable<decimal> OutputPricePerMillion { get; set; }
        public Nullable<decimal> InputCostUSD { get; set; }
        public Nullable<decimal> CachedInputCostUSD { get; set; }
        public Nullable<decimal> OutputCostUSD { get; set; }
        public Nullable<decimal> TotalCostUSD { get; set; }
        public bool CostCalculated { get; set; }
        public Nullable<int> ImageSizeBytes { get; set; }
        public Nullable<long> DurationMs { get; set; }
        public Nullable<int> HttpStatusCode { get; set; }
        public bool IsSuccess { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
