//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApiRequestLog
    {
        public long RowID { get; set; }
        public System.Guid RequestID { get; set; }
        public System.DateTime RequestTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<int> DurationMs { get; set; }
        public string UserID { get; set; }
        public string MerchantID { get; set; }
        public string HttpMethod { get; set; }
        public string RequestUrl { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public string RequestHeaders { get; set; }
        public string RequestBody { get; set; }
        public Nullable<int> ResponseStatusCode { get; set; }
        public string ResponseBody { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string ExceptionMessage { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Description { get; set; }
        public string ActivityTitle { get; set; }
    }
}
