//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Resource()
        {
            this.tbl_ResourceRole = new HashSet<tbl_ResourceRole>();
        }
    
        public long RowID { get; set; }
        public string MerchantID { get; set; }
        public string CategoryCode { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string FileUrl { get; set; }
        public string UploadedFile { get; set; }
        public string OriginalFileName { get; set; }
        public string StoredFileName { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<long> FileUploadAuditID { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
        public System.Guid PublicID { get; set; }
    
        public virtual tbl_FileUploadAudit tbl_FileUploadAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ResourceRole> tbl_ResourceRole { get; set; }
    }
}
