//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AgentRank
    {
        public long RowID { get; set; }
        public string RankName { get; set; }
        public int Ranking { get; set; }
        public int Status { get; set; }
        public string MerchantID { get; set; }
        public string RankCode { get; set; }
        public Nullable<bool> IsAutoRankEligible { get; set; }
    }
}
