//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustPlanWithdrawalConfig
    {
        public long RowID { get; set; }
        public long TrustPlanID { get; set; }
        public int LockInPeriod { get; set; }
        public string LockInPeriodUnit { get; set; }
        public bool AllowEarlyWithdrawal { get; set; }
        public string EarlyWithdrawalFeeType { get; set; }
        public Nullable<decimal> EarlyWithdrawalFeeValue { get; set; }
    }
}
