//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sms_History
    {
        public long RowID { get; set; }
        public string MerchantID { get; set; }
        public long MemberID { get; set; }
        public string Type { get; set; }
        public string SenderMobile { get; set; }
        public string SmsContent { get; set; }
        public string Reference { get; set; }
        public string ErrorRemark { get; set; }
        public string IP { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
    }
}
