//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileUploadAudit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FileUploadAudit()
        {
            this.tbl_Resource = new HashSet<tbl_Resource>();
        }
    
        public long RowID { get; set; }
        public string MerchantID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public string ModuleCode { get; set; }
        public string UploadType { get; set; }
        public string OriginalFileName { get; set; }
        public string StoredFileName { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string SHA256 { get; set; }
        public int ScanStatus { get; set; }
        public string ScanCode { get; set; }
        public string ScanMessage { get; set; }
        public Nullable<int> AntivirusExitCode { get; set; }
        public string FileUrl { get; set; }
        public string UploadedFile { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resource> tbl_Resource { get; set; }
    }
}
