//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_TrustDeedExecution
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public string SigningMethod { get; set; }
        public string SpecialCircumstance { get; set; }
        public string ReadOverBy { get; set; }
        public string ReadOverIdentityNo { get; set; }
        public string LanguageOrDialect { get; set; }
        public string RelationshipWithSettlor { get; set; }
        public string OtherRelationshipWithSettlor { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
    }
}
