//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role
    {
        public long RowID { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string UserType { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> AdminRank { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string MerchantID { get; set; }
    }
}
