//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country
    {
        public int Id { get; set; }
        public string Country_Name { get; set; }
        public string Country_Domain { get; set; }
        public Nullable<short> Country_Status { get; set; }
        public Nullable<int> Country_MobileCode { get; set; }
        public string Country_Nationality { get; set; }
        public string Currency_Code { get; set; }
        public string Currency_Name { get; set; }
        public Nullable<decimal> Currency_Display { get; set; }
        public Nullable<decimal> Currency_Actual_In { get; set; }
        public Nullable<decimal> Currency_Actual_Out { get; set; }
        public Nullable<int> Currency_Length { get; set; }
        public string Currency_Web_Format { get; set; }
        public string Currency_DB_Format { get; set; }
        public Nullable<decimal> Currency_BankCharges { get; set; }
    }
}
