//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_action
    {
        public long id { get; set; }
        public string action_sql { get; set; }
        public string action_type { get; set; }
        public string action_loginID { get; set; }
        public Nullable<System.DateTime> action_datetime { get; set; }
        public string action_ip { get; set; }
        public string action_browser { get; set; }
        public string action_browser_version { get; set; }
    }
}
