//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_SendMail
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Templete { get; set; }
        public string ActionType { get; set; }
        public long RefID { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public string Ip { get; set; }
        public string WalletType { get; set; }
    }
}
