//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_error
    {
        public long id { get; set; }
        public string error_message { get; set; }
        public string error_sql { get; set; }
        public string error_rawurl { get; set; }
        public string error_loginid { get; set; }
        public Nullable<System.DateTime> error_datetime { get; set; }
        public string error_ip { get; set; }
        public string error_browser { get; set; }
        public string error_browser_version { get; set; }
    }
}
