//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrustApplication()
        {
            this.tbl_TrustApplication_PersonalDetail = new HashSet<tbl_TrustApplication_PersonalDetail>();
            this.tbl_TrustApplication_SourceOfFund = new HashSet<tbl_TrustApplication_SourceOfFund>();
            this.tbl_TrustApplication_TrustAsset = new HashSet<tbl_TrustApplication_TrustAsset>();
            this.tbl_TrustApplication_BeneficiaryAllocation = new HashSet<tbl_TrustApplication_BeneficiaryAllocation>();
            this.tbl_TrustApplication_TrustDeedExecution = new HashSet<tbl_TrustApplication_TrustDeedExecution>();
            this.tbl_TrustApplication_CoBroker = new HashSet<tbl_TrustApplication_CoBroker>();
            this.tbl_TrustApplication_SupportingDocument = new HashSet<tbl_TrustApplication_SupportingDocument>();
            this.tbl_TrustApplication_Caretaker = new HashSet<tbl_TrustApplication_Caretaker>();
            this.tbl_TrustApplication_MinorDistribution = new HashSet<tbl_TrustApplication_MinorDistribution>();
            this.tbl_TrustApplication_Beneficiary = new HashSet<tbl_TrustApplication_Beneficiary>();
            this.tbl_TrustApplication_Payment = new HashSet<tbl_TrustApplication_Payment>();
            this.tbl_TrustApplication_StatusHistory = new HashSet<tbl_TrustApplication_StatusHistory>();
            this.tbl_TrustApplication_GeneratedDocument = new HashSet<tbl_TrustApplication_GeneratedDocument>();
            this.tbl_TrustApplication_PlanSnapshot = new HashSet<tbl_TrustApplication_PlanSnapshot>();
            this.tbl_TrustApplication_DividendSchedule = new HashSet<tbl_TrustApplication_DividendSchedule>();
            this.tbl_TrustApplication_History = new HashSet<tbl_TrustApplication_History>();
        }
    
        public long RowID { get; set; }
        public long TrustID { get; set; }
        public string MerchantID { get; set; }
        public string ProductCode { get; set; }
        public long MemberID { get; set; }
        public string ApplicationStatus { get; set; }
        public int CurrentStep { get; set; }
        public int LastCompletedStep { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public Nullable<long> SubmittedBy { get; set; }
        public bool HasCaretakerDistribution { get; set; }
        public Nullable<System.DateTime> CommencementDate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_PersonalDetail> tbl_TrustApplication_PersonalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_SourceOfFund> tbl_TrustApplication_SourceOfFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_TrustAsset> tbl_TrustApplication_TrustAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_BeneficiaryAllocation> tbl_TrustApplication_BeneficiaryAllocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_TrustDeedExecution> tbl_TrustApplication_TrustDeedExecution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_CoBroker> tbl_TrustApplication_CoBroker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_SupportingDocument> tbl_TrustApplication_SupportingDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_Caretaker> tbl_TrustApplication_Caretaker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_MinorDistribution> tbl_TrustApplication_MinorDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_Beneficiary> tbl_TrustApplication_Beneficiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_Payment> tbl_TrustApplication_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_StatusHistory> tbl_TrustApplication_StatusHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_GeneratedDocument> tbl_TrustApplication_GeneratedDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_PlanSnapshot> tbl_TrustApplication_PlanSnapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_DividendSchedule> tbl_TrustApplication_DividendSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_History> tbl_TrustApplication_History { get; set; }
    }
}
