//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_BeneficiaryAllocationDetail
    {
        public long RowID { get; set; }
        public long AllocationID { get; set; }
        public Nullable<long> BeneficiaryID { get; set; }
        public string RoleType { get; set; }
        public Nullable<decimal> AllocationPercentage { get; set; }
        public bool IsTrusteeCompany { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual tbl_TrustApplication_BeneficiaryAllocation tbl_TrustApplication_BeneficiaryAllocation { get; set; }
        public virtual tbl_TrustApplication_Beneficiary tbl_TrustApplication_Beneficiary { get; set; }
    }
}
