//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WalletCash
    {
        public long RowID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<long> FromUID { get; set; }
        public Nullable<long> ToID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string TransactionID { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> WalletType { get; set; }
        public string Remarks { get; set; }
        public string Record { get; set; }
        public Nullable<bool> OnHold { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string NType { get; set; }
    }
}
