//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_2Fa
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string SecretKey { get; set; }
        public int Status { get; set; }
    }
}
