//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_PersonalDetail
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public string FullName { get; set; }
        public string IdentityType { get; set; }
        public string IdentityNo { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsUSTaxPayer { get; set; }
        public Nullable<bool> HasOtherTaxResidence { get; set; }
        public string TaxResidenceCountry { get; set; }
        public string TaxIdentificationNo { get; set; }
        public string TINUnavailableReason { get; set; }
        public string TINUnavailableExplanation { get; set; }
        public string EmployerName { get; set; }
        public string NatureOfBusiness { get; set; }
        public string Occupation { get; set; }
        public string AnnualIncomeCode { get; set; }
        public string NetWorthCode { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
    }
}
