//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_BeneficiaryAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrustApplication_BeneficiaryAllocation()
        {
            this.tbl_TrustApplication_BeneficiaryAllocationDetail = new HashSet<tbl_TrustApplication_BeneficiaryAllocationDetail>();
        }
    
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public int AllocationType { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_BeneficiaryAllocationDetail> tbl_TrustApplication_BeneficiaryAllocationDetail { get; set; }
    }
}
