//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_PlanSnapshot
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public string ProductCode { get; set; }
        public int SnapshotVersion { get; set; }
        public string PlanConfigurationJson { get; set; }
        public string SnapshotHash { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public long CreatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
    }
}
