//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustPlanFee
    {
        public long RowID { get; set; }
        public long TrustPlanID { get; set; }
        public string FeeType { get; set; }
        public string RateType { get; set; }
        public decimal FeeValue { get; set; }
        public string ChargeTiming { get; set; }
    }
}
