//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Type_Of_Payment_To_Trustee
    {
        public long RowID { get; set; }
        public string Payment_To_Trustee_Code { get; set; }
        public string Payment_To_Trustee_Name { get; set; }
        public int Sort { get; set; }
        public int Status { get; set; }
    }
}
