//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parameter
    {
        public string category { get; set; }
        public string parameterName { get; set; }
        public string parameterValue { get; set; }
        public string remarks { get; set; }
        public Nullable<int> sorting { get; set; }
    }
}
