//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrustDocument()
        {
            this.tbl_TrustApplication_GeneratedDocument = new HashSet<tbl_TrustApplication_GeneratedDocument>();
            this.tbl_TrustDocumentAllocationMapping = new HashSet<tbl_TrustDocumentAllocationMapping>();
            this.tbl_TrustDocumentRole = new HashSet<tbl_TrustDocumentRole>();
            this.tbl_TrustDocumentTemplate = new HashSet<tbl_TrustDocumentTemplate>();
        }
    
        public long RowID { get; set; }
        public string DocumentCode { get; set; }
        public string DocumentName { get; set; }
        public string Description { get; set; }
        public string AvailableStage { get; set; }
        public string DocumentType { get; set; }
        public bool GenerateAutomatically { get; set; }
        public bool GenerateOnDemand { get; set; }
        public int GenerationOrder { get; set; }
        public int Sort { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_GeneratedDocument> tbl_TrustApplication_GeneratedDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustDocumentAllocationMapping> tbl_TrustDocumentAllocationMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustDocumentRole> tbl_TrustDocumentRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustDocumentTemplate> tbl_TrustDocumentTemplate { get; set; }
    }
}
