//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustDocumentTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrustDocumentTemplate()
        {
            this.tbl_TrustApplication_GeneratedDocument = new HashSet<tbl_TrustApplication_GeneratedDocument>();
        }
    
        public long RowID { get; set; }
        public long TrustDocumentID { get; set; }
        public string TemplateVersion { get; set; }
        public string TemplateType { get; set; }
        public string TemplatePath { get; set; }
        public string OutputFileNameFormat { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_GeneratedDocument> tbl_TrustApplication_GeneratedDocument { get; set; }
        public virtual tbl_TrustDocument tbl_TrustDocument { get; set; }
    }
}
