//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_DividendSchedule
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public int ScheduleNo { get; set; }
        public int ReturnYear { get; set; }
        public int PeriodNo { get; set; }
        public string DividendMethod { get; set; }
        public string PayoutFrequency { get; set; }
        public string CalculationStart { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
        public System.DateTime PayoutDate { get; set; }
        public decimal CalculationBasisAmount { get; set; }
        public decimal AnnualRate { get; set; }
        public decimal BaseDividendAmount { get; set; }
        public decimal BonusAmount { get; set; }
        public decimal TotalReturnAmount { get; set; }
        public string ReturnOption { get; set; }
        public decimal PayoutAmount { get; set; }
        public decimal RedepositAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
    }
}
