//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailQueue
    {
        public long RowID { get; set; }
        public string PublicID { get; set; }
        public string JobType { get; set; }
        public string ReceiverEmail { get; set; }
        public string Subject { get; set; }
        public string TemplateCode { get; set; }
        public string TemplateDataJson { get; set; }
        public int Status { get; set; }
        public int RetryCount { get; set; }
        public Nullable<System.DateTime> ErrorMessage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string MerchantID { get; set; }
    }
}
