//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_securityPassAttemp
    {
        public long id { get; set; }
        public string log_user { get; set; }
        public Nullable<long> log_userId { get; set; }
        public string log_ip { get; set; }
        public string log_sessionId { get; set; }
        public string log_action { get; set; }
        public string log_pwdAttempt { get; set; }
        public string log_browser { get; set; }
        public string log_version { get; set; }
        public Nullable<System.DateTime> log_datetime { get; set; }
        public int log_credit { get; set; }
        public int log_clearcredit { get; set; }
    }
}
