//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_GeneratedDocument
    {
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public long TrustDocumentID { get; set; }
        public long TrustDocumentTemplateID { get; set; }
        public string GenerationStatus { get; set; }
        public string OriginalFileName { get; set; }
        public string FileExtension { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileUrl { get; set; }
        public string GeneratedFile { get; set; }
        public string SHA256 { get; set; }
        public Nullable<System.DateTime> GeneratedAt { get; set; }
        public Nullable<long> GeneratedBy { get; set; }
        public string ErrorMessage { get; set; }
        public int RetryCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
        public virtual tbl_TrustDocument tbl_TrustDocument { get; set; }
        public virtual tbl_TrustDocumentTemplate tbl_TrustDocumentTemplate { get; set; }
    }
}
