//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MemberUnit
    {
        public long RowID { get; set; }
        public int memberID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> unitSponsor { get; set; }
        public string sponsorIndex { get; set; }
        public Nullable<int> levelx { get; set; }
        public string unitPosition { get; set; }
        public Nullable<int> unitUpline { get; set; }
        public string uplineIndex { get; set; }
        public Nullable<int> levelfx { get; set; }
        public Nullable<int> node { get; set; }
        public string placementtype { get; set; }
        public Nullable<bool> isActivated { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
