//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_sql
    {
        public long id { get; set; }
        public string sqlString { get; set; }
        public string fromURL { get; set; }
        public string loginID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
