//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChecksumBalance
    {
        public long RowID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<int> PointType { get; set; }
        public string type { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
