//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public long RowID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public string LoginPassword { get; set; }
        public string SecondaryPassword { get; set; }
        public Nullable<System.DateTime> LastTimeLogin { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<bool> LoginStatus { get; set; }
        public string LoginRole { get; set; }
        public string login_langcode { get; set; }
        public Nullable<bool> FirstLogin { get; set; }
        public Nullable<System.DateTime> renewalDate { get; set; }
        public Nullable<System.DateTime> BlockedAt { get; set; }
        public Nullable<System.DateTime> ReactiveAt { get; set; }
    }
}
