//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MemberControl
    {
        public int RowID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public int ChangePass { get; set; }
        public int ChangeSecurePass { get; set; }
        public int ChangeProfile { get; set; }
        public int ChangeBank { get; set; }
        public int Email_Verification_Status { get; set; }
        public int KYC_Verification_Status { get; set; }
        public decimal Comm { get; set; }
        public int TrustAccess { get; set; }
        public int WillAccess { get; set; }
    }
}
