//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_BankList
    {
        public long RowID { get; set; }
        public string Country { get; set; }
        public string Country_Domain { get; set; }
        public string Currency { get; set; }
        public string BankName { get; set; }
        public string BankNameDetail { get; set; }
        public string ShowOption { get; set; }
        public string OperateMethod { get; set; }
        public int Status { get; set; }
        public string ImgPath { get; set; }
        public string NoticeImg { get; set; }
        public int IsDeposit { get; set; }
        public int IsWithdrawal { get; set; }
    }
}
