//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Current_Login
    {
        public long id { get; set; }
        public string user_session { get; set; }
        public string member_code { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public Nullable<System.DateTime> last_activity { get; set; }
        public string current_page { get; set; }
        public string user_ip { get; set; }
    }
}
