//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegistrationSession
    {
        public long RowID { get; set; }
        public System.Guid SessionID { get; set; }
        public string TokenHash { get; set; }
        public string ReferralCode { get; set; }
        public string MerchantID { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public Nullable<System.DateTime> LastActivityAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string CreatedIP { get; set; }
    }
}
