//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RememberMeToken
    {
        public long RowID { get; set; }
        public long MemberID { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsRevoked { get; set; }
    }
}
