//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrustApplication_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrustApplication_Payment()
        {
            this.tbl_TrustApplication_PaymentDocument = new HashSet<tbl_TrustApplication_PaymentDocument>();
        }
    
        public long RowID { get; set; }
        public long TrustApplicationID { get; set; }
        public int PaymentNo { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReferenceNo { get; set; }
        public string PaymentStatus { get; set; }
        public string FinanceRemark { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual tbl_TrustApplication tbl_TrustApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrustApplication_PaymentDocument> tbl_TrustApplication_PaymentDocument { get; set; }
    }
}
