//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CPX.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MemberInfo
    {
        public long RowID { get; set; }
        public string displayName { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> AdvanceRanking { get; set; }
        public string IC_Type { get; set; }
        public string IC { get; set; }
        public string Email { get; set; }
        public string CountryMobileCode { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country_Domain { get; set; }
        public string Country { get; set; }
        public string Occupation { get; set; }
        public string TinNumber { get; set; }
        public string Currency { get; set; }
        public string AccType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string RefID { get; set; }
    }
}
